### ISSUE TITLE
JTube-2.0.1, 2.03-the application crashes on Nokia C3-00

### ISSUE THREAD

**Issue by Unlimited2018** [shinovon/JTube#13]
The application opens on the Nokia C3-00 phone, you can search for the video but when you press Watch the application crashes! JTube 2.0 works perfectly on Nokia C3-00 but the update notification is stressful :( Thanks for the JTube application, it's the only way I can watch yotube on my phone!

**Comment by R0ci0-V3rd3al** [comment]
Did you give the app permissions?

**Comment by shinovon** [comment]
I didn't change anything in 2.0.1 related to video playback. Check your app settings, video playback mode must be set to "via browser"

**Comment by R0ci0-V3rd3al** [comment]
to disable update notification go to opts (options) > setting> check for updates (off) > apply

**Comment by R0ci0-V3rd3al** [comment]
and to view them you must download them and specify a path for download through for that can open in the native player after download download can be opened. if you want to watch it online rtsp use "via 2yxa.mobi" to convert it online

**Comment by Unlimited2018** [comment]
I tried what wrote here but the application still crashes, I leave the error that appears on the screen. Thanks for "check for updates (disabled)> app" I didn't see the option when searching through settings
![1](https://user-images.githubusercontent.com/37028908/172906734-c935d789-9dde-4826-9234-9746f36e8ed5.jpg)
.

**Comment by shinovon** [comment]
Check this
[JTube.zip](https://github.com/shinovon/JTube/files/8872642/JTube.zip)

**Comment by Unlimited2018** [comment]
The same error appears on the screen!

**Comment by shinovon** [comment]
Update to the latest version.

**Comment by Unlimited2018** [comment]
It works now! Thanks!
