### ISSUE TITLE
Design suggestions for JTube.

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#18]
_Suggestions can be updated. Check the date. 05/07/22_
+ The start of the application.
*1. Classic design. Search bar up, down suggestions in list mode.
*2. Search bar up, down suggestions in grid mode.
*3. Search bar up, down suggestions in [coverflow](https://www.google.com/search?q=coverflow+example&tbm=isch&hl=en-US) mode. Then 1 or 2 buttons can be added for options.
*4. Keep the search bar static in any window.
![0](https://user-images.githubusercontent.com/72929651/177453027-55183db3-f734-45fa-a929-134c0de23027.png)

+ Shortcuts for phones with keyboard. Each option in the application should be assigned to a key on the phone. 12 [phone keys](https://www.google.com/search?q=keys+phone&tbm=isch&hl=en) for 12 shortcuts.
![00](https://user-images.githubusercontent.com/72929651/177455866-269ba023-3ebb-47ba-880e-96064fef67ca.png)

+ Floating windows for options or menu. Currently in Jtube 2.0.5, when accessing the menu or options opens another screen.
*Instead of switching screens, a floating window should appear above the interface.
![00](https://user-images.githubusercontent.com/72929651/177457227-0bb4d0c1-0355-4955-826f-41709fda9a95.jpg)

+ Improve interface visualization. Change the colors to gold (In dark mode) for: Video name, channel, playlist, views, date, time.
*Or select the color you want.

+ More information. This was the design of the yotube application in java.
*1. Video - Java app.
-https://www.youtube.com/watch?v=h02LcEJ8Q6o
-https://www.youtube.com/watch?v=o0ljWtG1xOM
*2. Video - Web app.
-https://www.youtube.com/watch?v=5oMzDAsYjt8
*3. Images of the app.
-https://www.google.com/search?q=youtube+mobile+j2me&tbm=isch&hl=en&tbs=rimg%3ACeYq-7rXBgMQYeKuwV05vCSs8AEAsgIMCgIIABAAOgQIABAA
-https://yandex.com/images/search?url=https%3A%2F%2Favatars.mds.yandex.net%2Fget-images-cbir%2F2493848%2FwKcf5xcCMk1ijEYMLN-f0A8306%2Forig&rpt=imageview&cbir_id=2493848%2FwKcf5xcCMk1ijEYMLN-f0A8306&cbir_page=similar

**Comment by huhungahuru** [comment]
@shinovon 
![00](https://user-images.githubusercontent.com/72929651/180616812-7f620541-dcdc-4c09-b84e-fecfcbe3b0e7.png)

**Comment by shinovon** [comment]
![IMG_20220723_225213_174](https://user-images.githubusercontent.com/43963888/180617053-17cad233-da1f-466a-82f9-6feb9c319cc9.jpg)

**Comment by shinovon** [comment]
![20220723_225445](https://user-images.githubusercontent.com/43963888/180617162-67202369-3942-451b-8e33-bf93e16f1090.jpg)

**Comment by huhungahuru** [comment]
![0](https://user-images.githubusercontent.com/72929651/180619214-1573b6a3-72e2-4012-aaf4-2c228a255fe8.png)
