### ISSUE TITLE
Error playing 360p videos.

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#23]
On S40 phones, 360p video playback is supported. On Asha phones, they support videos in 360p and up to 480.
+ On an Asha phone when watching a video from Jtube in 360p, the video only plays the audio.
*On the black screen, only a message appears: Video is not supported.

**Comment by shinovon** [comment]
S40 does not support the video codec used by YouTube

**Comment by huhungahuru** [comment]
@shinovon Can't this video codec be integrated into JTube to support video playback?

**Comment by shinovon** [comment]
No.
