### ISSUE TITLE
Language display support with special characters and emojis.

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#25]
_Suggestions can be updated. Check the date. 05/07/22_

+ When viewing an East Asian language (chinese, japanese, korean), only squares are displayed.
*I don't know if the same happens with other languages like hindi, arabic, etc.
*Emojis and symbols also look square.
![000](https://user-images.githubusercontent.com/72929651/177480484-da351a07-2430-402d-8c34-455823155eba.png)

**Comment by shinovon** [comment]
It depends on the device font
