### ISSUE TITLE
Translation of languages.

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#3]
-What program is used for language translation?

**Is it possible to adapt an API to the old Java application of Youtube, so that it currently works?
Or any way to make this app work?
https://www.youtube.com/watch?v=YkAZy5m46lc&t=232s
https://googlesystem.blogspot.com/2008/01/mobile-youtube-application.html

**Comment by shinovon** [comment]
> -What program is used for language translation?
https://github.com/shinovon/jtlngedit

**Comment by huhungahuru** [comment]
In the LocalizationTableModel.java file, only the Russian language is replaced by which one wishes? or
in all the files, the words that are between "" must be translated.

**Comment by shinovon** [comment]
Use this: https://t.me/nnmidletschat/2688

**Comment by huhungahuru** [comment]
> Usa esto: [https://t.me/nnmidletschat/2688 ](https://t.me/nnmidletschat/2688)

Add the file jtlangeditor.jar in https://github.com/shinovon/jtlngedit. It is more accessible to the download.
Add a manual for translation.

You didn't answer the question.

> In the LocalizationTableModel.java file, only the Russian language is replaced by which one wishes? or in all the files, the words that are between "" must be translated.

**Comment by shinovon** [comment]
> You didn't answer the question.
> 
> > In the LocalizationTableModel.java file, only the Russian language is replaced by which one wishes? or in all the files, the words that are between "" must be translated.

There is no need for this.

> Add a manual for translation.

UI is very simple
![Screenshot_20220207-093552_Telegram](https://user-images.githubusercontent.com/43963888/152725199-e788230b-c346-4f50-8f86-d50f6b9a2c24.jpg)

**Comment by YOSI-COHEN** [comment]
Where do I download this software?
And which files do I need to translate for the Hebrew language

post Scriptum. I don't have a Telegram account
