### ISSUE TITLE
Add the Previous and Next page buttons.

### ISSUE THREAD

**Issue by ghost** [shinovon/JTube#35]
Because the content displayed or when searching has a limit, the Previous and Next page buttons should be added.
And if you can go listing the pages.
*Since the application does not support infinite scroll.
![00](https://user-images.githubusercontent.com/72929651/177539138-15458ffb-63bd-4f87-89c1-599cd789c937.png)

**Comment by shinovon** [comment]
It's impossible with current invidious API, I have tried that.
