### ISSUE TITLE
Sort the interface options. 

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#4]
Currently the options are:
-View
-About
-Settings
-Switch to popular
-Search
-Open by ID

The order that is proposed is (it will improve accessibility):
-View
-Search
-Switch to popular
-Open by ID
-Settings
-About

Add a ComboBox to the language setting.
Someone who uses the app for the first time does not know how to change the language. Or which ones are available.

**Comment by huhungahuru** [comment]
When choosing a video, the options are:
-View
-Settings
-Download

The order that is proposed is:
-View
-Download
-Settings

**Comment by shinovon** [comment]
Each platform sorts commands differently, there is no way to fix this, i think.

**Comment by Feodor0090** [comment]
The third argument in `Command` constructor should do that.
