### ISSUE TITLE
DASH (Dynamic Adaptive Streaming over HTTP).

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#42]
Now [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) is used as the preferred means for videos playback on NewPipe instead of [progressive HTTP](https://en.wikipedia.org/wiki/Progressive_download), improving loading times in playback and seeking.
*Maybe DASH can be used in JTube, to improve load times in playback and search.
-https://newpipe.net/blog/pinned/release/newpipe-0.23.1/
-https://github.com/TeamNewPipe/NewPipe/commit/210834fbe933654804016e547833288f90e2135e
-https://github.com/TeamNewPipe/NewPipe/commits?author=AudricV
-https://github.com/TeamNewPipe/NewPipe/pull/8153

**Comment by shinovon** [comment]
Symbian can't handle DASH
