### ISSUE TITLE
Freezing when playing videos.

### ISSUE THREAD

**Issue by ghost** [shinovon/JTube#43]
This error was present in previous versions of JTube. This error occurs:
-When watching 10-minute videos. It freezes after 6 or 7 minutes.
-Videos of 45 minutes or more. It can be frozen between 15 to 30 minutes.
*You have to close the video player, reopen the video and locate the time (minute) where it froze to continue watching.

**Comment by shinovon** [comment]
This is a known issue, to avoid this you must download the video and then watch it or use the browser method.

**Comment by shinovon** [comment]
Fixed
