### ISSUE TITLE
Error in the syntax of the video date.

### ISSUE THREAD

**Issue by huhungahuru** [shinovon/JTube#48]
In the german, spanish, portuguese languages, "ago" comes first, then the "number" and then "days, months or years" (it can be viewed on the same youtube when switching languages).
*Example: ago 2 days (it does not apply for english and russian).
![0](https://user-images.githubusercontent.com/72929651/179334514-67a8efd3-65ef-4f6e-a242-0a1cff9de023.png)
In version 2.1.0 it was fine, but in version 2.1.1 this error appears.

**Comment by shinovon** [comment]
Reverted 'Dates localization' commit

**Comment by huhungahuru** [comment]
@shinovon Above... jtlngedit 1.0.6(2.1.1) it was used in jtube 2.1.0. In jtlngedit 2.2 the date translation was removed.
