### ISSUE TITLE
Added Hebrew language

### ISSUE THREAD

**Issue by YOSI-COHEN** [shinovon/JTube#53]
Hello.
First I want to thank you for the application, I have been looking for a very long time for an application like this.
until i found you

I have two requests from you:
A. Please add the Hebrew language in the next update
B. Make it possible to search by link.

Everything else is great!
Again, thank you.

**Comment by YOSI-COHEN** [comment]
Thank you.
In the last few days I translated the file through the application in a somewhat primitive way into Hebrew.
I'll upload it soon, it's on my phone now

**Comment by YOSI-COHEN** [comment]
I would be happy for you to create the application with the Hebrew language for me in the meantime.

(And if you can give a link to my channel in about:
https://www.youtube.com/channel/UCtkvQIBp0T4xZ0b8xhYOSCA)
This is the translated file:
[jtlng.zip](https://github.com/shinovon/JTube/files/9350095/jtlng.zip)

**Comment by shinovon** [comment]
J2ME version of editor: https://t.me/nnmidletschat/2327

**Comment by YOSI-COHEN** [comment]
Oh, well...
Do I need to re-translate?!

Can you upload the software for me from Telegram, I don't have a Telegram account

**Comment by YOSI-COHEN** [comment]
I don't have the strength to translate again...

Can you upload the software for me from Telegram, I don't have a Telegram account




> גרסת J2ME של עורך: https://t.me/nnmidletschat/2327

**Comment by shinovon** [comment]
[j2melngedit2.2.0.jar.zip](https://github.com/shinovon/JTube/files/9350808/j2melngedit2.2.0.jar.zip)

**Comment by shinovon** [comment]
You may import your old language file, if you replace '.' with '_' in file name

**Comment by YOSI-COHEN** [comment]
> [j2melngedit2.2.0.jar.zip](https://github.com/shinovon/JTube/files/9350808/j2melngedit2.2.0.jar.zip)

Hey
When I run the application the application crashes and shows an error

**Comment by WunderWungiel** [comment]
@YOSI-COHEN Do you have Java installed?

**Comment by WunderWungiel** [comment]
Do you try to run it on PC or phone?

**Comment by YOSI-COHEN** [comment]
> Do you try to run it on PC or phone?

on the phone
And the Symbian 9.3 cell phone supports Java


 @shinovon 

Give me the text file, and I'll try to translate manually

> Do you try to run it on PC or phone?

on the phone
And the Symbian 9.3 cell phone supports Java
