### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by YOSI-COHEN** [shinovon/JTube#54]
Two more bugs I encountered:
A. When I download a video, it says that the size of the video is 40MB, but in reality it downloads up to 70MB and more, and the percentages climb to 120 percent
B. When I download audio, the application shows an error.

Thanks.

**Comment by shinovon** [comment]
> When I download audio, the application shows an error.

This means that codec is not supported

**Comment by shinovon** [comment]
B is fixed in 2.4.1
