### ISSUE TITLE
error java.io.IOException

### ISSUE THREAD

**Issue by g-horakhty** [shinovon/JTube#56]
error java.io.IOException: 302 Found

e: 10
at b
t: Thread-507218944
URL: v1/popular?region=US&fields=title,videold, author,error, errorBacktrace, code

Device: Blackberry curve 9300

**Comment by Erick256lm** [comment]
i tried it on my nokia e5 and it worked

control panel>data manager>application manager>installed apps>
press jtube options, settings and try to change some internet settings such as access point or authorizations
