### ISSUE TITLE
Advanced browser for Nokia

### ISSUE THREAD

**Issue by YOSI-COHEN** [shinovon/JTube#58]
After your huge success on YouTube and the translation for Nokia (something that helps people a lot).

We would appreciate it if you would also make a browser for Nokia that would at least support,
- Viewing\downloading files on YouTube
- Downloading large files (more than 100 megabytes)
- and many more nice inclusions, such as access to most websites, etc.
Thank you.

post Scriptum. - A small bug, in the latest version, it doesn't show me the channel.

Thanks for everything

**Comment by WunderWungiel** [comment]
@YOSI-COHEN Web browser?! 😱

**Comment by KOT4N** [comment]
@YOSI-COHEN web browser in yt client? Wtf

**Comment by YOSI-COHEN** [comment]
Have a web browser in general
I would not object

**Comment by KOT4N** [comment]
@YOSI-COHEN it's a YOUTUBE CLIENT, why it need a browser?

**Comment by YOSI-COHEN** [comment]
I'm asking in general
If the developer could also make a JAR browser, regardless of YouTube

**Comment by KOT4N** [comment]
@YOSI-COHEN bruh

**Comment by YOSI-COHEN** [comment]
?

**Comment by KOT4N** [comment]
@YOSI-COHEN why you asking about it in YT client issues?

**Comment by YOSI-COHEN** [comment]
I don't know where to ask

**Comment by dimon495** [comment]
@WunderWungiel и как это сделать
