### ISSUE TITLE
No sound when playing video.

### ISSUE THREAD

**Issue by omerxxd** [shinovon/JTube#59]
I have Nokia 6303i Classic runs on an S40 6th edition and when it is playing a video on Jtube theres no sound. I think it is a codec issue. I am playig videos at 144p and via browser option.  Can I fix this problem myself or is it a bug?

**Comment by R0ci0-V3rd3al** [comment]
Maybe it could be... but here I have 201 and I don't have that audio problem... although some 144px videos in 3gp can't be downloaded

**Comment by omerxxd** [comment]
> Maybe it could be... but here I have 201 and I don't have that audio problem... although some 144px videos in 3gp can't be downloaded

I have Asha 201 too and for me it is downloading the video first and then i can watch the video. But on 6303i i don't have to wait for download. Video plays instantly but sadly there's no sound

**Comment by shinovon** [comment]
Read FAQ
