### ISSUE TITLE
Videos are not playing.

### ISSUE THREAD

**Issue by omerxxd** [shinovon/JTube#68]
I use Jtube on Nokia E6 Symbian Belle Refresh. Jtube homescreen loads as normal but videos are not playing. I tried reinstalling but it did not help. It says General: System Error.
![Scr000126](https://github.com/shinovon/JTube/assets/125218302/78d5e43a-113c-4643-9e87-f5208089893a)
![Scr000127](https://github.com/shinovon/JTube/assets/125218302/607c082b-c008-4566-9455-74bf7e28c2c9)

**Comment by shinovon** [comment]
Turn off second option in network settings
