### ISSUE TITLE
The software does not work

### ISSUE THREAD

**Issue by YOSI-COHEN** [shinovon/JTube#74]
It shows an error when you enter it

**Comment by shinovon** [comment]
Screenshot of an error?

**Comment by YOSI-COHEN** [comment]
NO Screenshot 
I DONT KNOW

**Comment by YOSI-COHEN** [comment]
why is not it working???????

**Comment by YOSI-COHEN** [comment]
![צילום מסך0020](https://github.com/shinovon/JTube/assets/82176699/a38f2aa0-2f04-4326-a3ba-353b57f4139e)

**Comment by shinovon** [comment]
Incorrect network access point is chosen

**Comment by YOSI-COHEN** [comment]
How to change an access point

**Comment by dimon495** [comment]
@YOSI-COHEN лес срать ёлка светофор

**Comment by shinovon** [comment]
> How to change an access point

https://github.com/shinovon/JTube/blob/master/FAQ.md
`Set network access point for the JTube in App Mgr. (9.2-9.4)`

**Comment by YOSI-COHEN** [comment]
How do I set up a Wi-Fi access point?
