### ISSUE TITLE
Videos download in the wrong resolution

### ISSUE THREAD

**Issue by SuperBlocks26** [shinovon/JTube#78]
I use jtube on a Nokia asha 306, and it has functioned wonderfully until recently. 
Recently it has been downloading all videos in 360 resolution even when I choose 144 resolution in settings. This is true even for videos I had previously downloaded in 144 resolution. (The phone I'm using doesn't support 360 resolution videos)
I hope that this isn't too much of a bother, and that this is the right way to communicate the issue.

**Comment by shinovon** [comment]
144p option is now removed, google is no longer returning its url.
